Updates

diff --git a/Softwares/astrodepth_prior_extraction_photometry b/Softwares/astrodepth_prior_extraction_photometry
--- a/Softwares/astrodepth_prior_extraction_photometry
+++ b/Softwares/astrodepth_prior_extraction_photometry
@@ -453,9 +453,10 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
     if [[ ! -f "image_check.sh" ]] || [[ " ${AstroDepth_INP_OVERWRITE[@]} " =~ " image_check " ]]; then
         echo "#!/bin/bash" > "image_check.sh"
         echo "source \"$AstroDepth_ScriptDir/SETUP.bash\"" >> "image_check.sh"
-        echo "CrabFitsImageArithmetic image_sci_input.fits times '+1.0' image_sci.fits      -remove-nan" >> "image_check.sh"
-        echo "CrabFitsImageArithmetic image_sci_input.fits times '-1.0' image_negative_input.fits"       >> "image_check.sh" #<20180222>#
-        echo "CrabFitsImageArithmetic image_sci_input.fits times '-1.0' image_negative.fits -remove-nan" >> "image_check.sh"
+        echo "CrabFitsImageArithmetic image_sci_input.fits times '+1.0' image_sci.fits      -remove-nan"  >> "image_check.sh"
+        echo "CrabFitsImageArithmetic image_sci_input.fits '!=' image_sci_input.fits image_nan_mask.fits" >> "image_check.sh"
+        echo "CrabFitsImageArithmetic image_sci_input.fits times '-1.0' image_negative_input.fits"        >> "image_check.sh" #<20180222>#
+        echo "CrabFitsImageArithmetic image_sci_input.fits times '-1.0' image_negative.fits -remove-nan"  >> "image_check.sh"
         # 
         if [[ ! -f "image_rms_input.fits" ]]; then
             echo "CrabFitsImageArithmetic image_sci.fits times 0.0 image_zero.fits -remove-nan"  >> "image_check.sh"
@@ -479,7 +480,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
     if [[ ! -f "image_sci.fits" ]]; then
         echo "***************************************************************************"
         echo "Error! Failed to run CrabFitsImageArithmetic and create \"image_sci.fits\"!"
-        echo "Please chec \"image_check.log\"!"
+        echo "Please check \"$(pwd)/image_check.log\"!"
         echo "***************************************************************************"
         exit 1
     fi
@@ -487,8 +488,16 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
     if [[ ! -f "image_rms.fits" ]]; then
         echo "***************************************************************************"
         echo "Error! Failed to run CrabFitsImageArithmetic and create \"image_rms.fits\"!"
-        echo "Please chec \"image_check.log\"!"
+        echo "Please check \"$(pwd)/image_check.log\"!"
         echo "***************************************************************************"
+        exit 1
+    fi
+    # 
+    if [[ ! -f "image_nan_mask.fits" ]]; then
+        echo "********************************************************************************"
+        echo "Error! Failed to run CrabFitsImageArithmetic and create \"image_nan_mask.fits\"!"
+        echo "Please check \"$(pwd)/image_check.log\"!"
+        echo "********************************************************************************"
         exit 1
     fi
     # 
